#!/usr/bin/env bash
# shellcheck disable=SC2086
# Display information about subdomains

domain="$1"
subdomain="$2"
default_subdomains=("www" "lb-01" "web-01" "web-02")

check_subdomain() {
    local sub="$1"
    local rec
    local dest

    # Use dig to extract information from DNS lookup
    args=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:/ { getline; print $4, $5 }')
	read -r rec dest <<< "$args"

    # Print the result
    echo "The subdomain $sub is a $rec record and points to $dest"
}

# Check subdomain if provided, otherwise check default subdomains
if [ -n "$subdomain" ]; then
    check_subdomain "$subdomain"
else
    for sub in "${default_subdomains[@]}"; do
        check_subdomain "$sub"
    done
fi

