#!/usr/bin/env bash
#configure HAProxy on lb-01 server

# Install HAproxy
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*

# Configure HAproxy
printf '%s\n' "frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 54.157.139.40:80 check
    server web-02 34.229.184.203:80 check" >> /etc/haproxy/haproxy.cfg
	
# Start HAproxy service
service haproxy restart
