#!/usr/bin/env bash
# display a string indefinitely, sleep 2 seconds between itervals
# display "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
