#!/usr/bin/env bash

idx=1

while [ $idx -le 100 ]
do
	if [ $((idx % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
	elif [ $((idx % 3)) -eq 0 ]
    then
        echo "Fizz"
	elif [ $((idx % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo $idx
    fi
    ((idx++))
done
