#!/usr/bin/env bash
# Displays Best School 10 times using while
# adds "Hi" after 9th line

idx=0

while [ $idx -lt 10 ]
do
	echo "Best School"
	((idx++))

	if [ $idx -eq 9 ]
	then
		echo "Hi"
	fi
done
