#!/usr/bin/env bash
# loops 10 times using while
# displays "bad luck" on line 4 
# displays "good luck" on line 8
# displays "Best School" on every other line

idx=1

while [ $idx -ne 10 ]
do
	if [ $idx -eq 4 ]
	then
		echo "bad luck"
	elif [ $idx -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((idx++))
done
