#!/usr/bin/env bash

idx=1

while [ $idx -le 20 ]
do
	echo "$idx"
	if [ $idx == 4 ]
	then
		echo "bad luck from China"
	elif [ $idx == 9 ]
	then
		echo "bad luck from Japan"
	elif [ $idx == 17 ]
	then
		echo "bad luck from Italy"
	fi
	((idx++))
done
