#!/usr/bin/env bash
# loops 20 times using while, use "case"
# displays "bad luck from China" on line 4 
# displays "bad luck from Japan" on line 9
# displays "bad luck from Italy" on line 17
# display current index before any string

idx=1
while [ $idx -le 20 ]
do
    echo $idx
    case $idx in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
    esac
    ((idx++))
done
