#!/usr/bin/env bash
# Run whoami command with given user argument.

# Check if a username argument is provided
if [ -z "$1" ]; then
  exit 1
fi

# Run the whoami command for the specified user
sudo -u "$1" whoami
