#!/usr/bin/env bash
# Run Nginx as the nginx user with limited permissions listening on port 8080.
sed -i 's|#user www-data|user nginx|' /etc/nginx/nginx.conf
sed -i "s|listen 80|listen 8080|g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
